### ISSUE TITLE
글쓰기 상호작용 UI 구현

### ISSUE THREAD

**Issue by minjeongss** [prgrms-fe-devcourse/NFE1-1-3-Calmiary#11]
## 💡Description
글쓰기 페이지에서 사용자와 상호작용이 있는 UI를 구현한다.

## ✅ Tasks
- [x] 로딩 스피너 구현
- [x] react-hook-form을 이용한 사용자 정보 입력 구현 
  - [x] 감정 입력
  - [x] 고민 입력
- [x] 사용자 감정 입력 클릭시 위로 이동 
- [x] 사용자 감정 및 고민 입력시 입력창 사라짐
- [x] 질의응답 시간 지연을 활용해 순차적으로 뜨도록 구현
