### ISSUE TITLE
다이어리 DetailPage UI 구현

### ISSUE THREAD

**Issue by Winter-Climbing** [prgrms-fe-devcourse/NFE1-1-3-Calmiary#17]
## 💡Description

다이어리 DetailPage UI 구조 구현
로그인 구현 전까지 정적 데이터 활용

## ✅ Tasks

 - [ ] info 툴팁 UI 구현
 - [x] #31
 - [x] 나의 고민 UI 구현
 - [x] Calminary 답변 UI 구현
