### ISSUE TITLE
글쓰기 UI 구현

### ISSUE THREAD

**Issue by minjeongss** [prgrms-fe-devcourse/NFE1-1-3-Calmiary#2]
## 💡Description
글쓰기 부분에서 상호작용 없는 UI 구조를 구현한다.

## ✅ Tasks
- [x] 고민을 물어보는 메시지 UI 구현
- [x] 사용자 입력 메시지 UI 구현
- [x] 사용자 감정 입력 UI 구현
- [x] 사용자 텍스트 입력 UI 구현
- [x] 배경 이미지(구름) 적용
- [x] 고민 공유하는 버튼 UI 구현
- [x] 메인으로 돌아가는 버튼 UI 구현
