### ISSUE TITLE
프로필 관련 API 구현

### ISSUE THREAD

**Issue by ruehan** [prgrms-fe-devcourse/NFE1-1-3-Calmiary#27]
## 💡Description

프로필에서 사용되는 API를 구현한다.

## ✅ Tasks
- [x] 공감한 고민 불러오기
- [x] 공유된 고민 불러오기
- [x] 회원 정보 수정
- [x] 탈퇴하기
