### ISSUE TITLE
백엔드 전체 코드 리팩토링 및 일관성 유지

### ISSUE THREAD

**Issue by ruehan** [prgrms-fe-devcourse/NFE1-1-3-Calmiary#29]
## 💡Description

백엔드 전체 코드에 대한 리팩토링을 진행하고 API의 일관성 유지를 진행한다.

## ✅ Tasks
- [x] 코드 리팩토링
- [x] API 문서 수정 
- [x] API 일관성 유지
- [x] DB Editor(Viewer) 수정
