### ISSUE TITLE
데이터베이스 스키마 구현

### ISSUE THREAD

**Issue by ruehan** [prgrms-fe-devcourse/NFE1-1-3-Calmiary#3]
## 💡Description

프로젝트에서 사용되는 데이터베이스의 스키마를 구현한다.

## ✅ Tasks
- [ ] User 스키마 구현
- [ ] Posts 스키마 구현
- [ ] Like 스키마 구현
- [ ] Comment 스키마 구현
