### ISSUE TITLE
글쓰기 API POST 응답에 대한 AI 답변 띄우기 구현

### ISSUE THREAD

**Issue by minjeongss** [prgrms-fe-devcourse/NFE1-1-3-Calmiary#36]
## 💡Description
연결한 API로부터 POST를 진행한 후, 받은 답변을 AI 답변에 저장하여 화면에 보여준다.

## ✅ Tasks

- [x] 서버로부터 정보 전송에 대한 응답 받기 전까지 로딩 스피너 제시
- [x] 서버로부터 정보 전송에 대한 응답을 AI 응답으로 저장
- [x] 로딩 스피너를 false로 설정하고, AI 응답 제시
