### ISSUE TITLE
데이터베이스 스키마 구현

### ISSUE THREAD

**Issue by ruehan** [prgrms-fe-devcourse/NFE1-1-3-Calmiary#4]
## 💡Description

프로젝트에서 사용되는 데이터베이스의 스키마를 구현한다.
API 테스트를 위한 앤드포인트를 구현한다.
API를 문서화한다.

[API Document](https://calmiary-be.org/)

## ✅ Tasks
- [x] User 스키마 구현
- [x] Posts 스키마 구현
- [x] Like 스키마 구현
- [x] Comment 스키마 구현
- [x] API 문서 작성 
- [x] 앤드포인트 구현
