### ISSUE TITLE
글쓰기 페이지 다른 페이지로 이동 및 이동과 관련된 API 연결

### ISSUE THREAD

**Issue by minjeongss** [prgrms-fe-devcourse/NFE1-1-3-Calmiary#47]
## 💡Description
글쓰기 페이지에서 다른 페이지로 이동하며, 이동과 관련된 API를 연결한다.

## ✅ Tasks

- [x] 내 고민 공유하기 확인 버튼을 누르면, 커뮤니티의 해당 고민 컨텐츠 페이지로 이동
- [x] 메인으로 가기 버튼을 누르면, growth 페이지로 이동
- [x] 로그인 > 글쓰기 페이지로 이동해, user_id 정보 Cookie와 연동
- [x] 글쓰기 > 메인 > 글쓰기로 돌아가면 writing 다시 뜨는 문제 해결
- [x] 정보 전송에 에러가 뜨면 고민 공개가 아닌 고민 재등록 버튼 뜨도록 변경
