### ISSUE TITLE
다이어리 MainPage UI 구현

### ISSUE THREAD

**Issue by Winter-Climbing** [prgrms-fe-devcourse/NFE1-1-3-Calmiary#5]
## 💡Description
다이어리 UI 구조 구현
로그인 구현 전까지 정적 데이터 활용

## ✅ Tasks
- [x] 레이아웃 설정
- [x] 헤더 UI 구현
- [x] 필터 UI 구현
- [x] 월별 UI 구현
- [x] 이모지 UI 구현
