### ISSUE TITLE
Navigation bar 구현

### ISSUE THREAD

**Issue by minjeongss** [prgrms-fe-devcourse/NFE1-1-3-Calmiary#59]
## 💡Description
하단의 Navigation bar를 구현한다.

## ✅ Tasks

- [x] Navigation bar UI 구현
- [x] Navigation bar Link 연결
- [x] Writing으로 이동했을 때, 화면 새로고침 되도록 설정
- [x] Navigation bar를 상위 컴포넌트에 배치해, 하위 컴포넌트에 추가적으로 불러오지 않아도 되도록 설정
  - [x] createbrowserrouter 활용!
