### ISSUE TITLE
글쓸 때 mutattion에 의한 CORS 문제 해결 및 CSS 처리

### ISSUE THREAD

**Issue by minjeongss** [prgrms-fe-devcourse/NFE1-1-3-Calmiary#68]
## 💡Description
글쓸 때, post를 mutation을 사용해 CORS 문제가 발생했다.
mutation 부분을 삭제하고, axios만 사용하도록 설정할 예정이다.
추가로 App.tsx에 생성한 Layout에 의해 페이지가 밀리는 부분의 CSS 처리를 진행할 예정이다.

## ✅ Tasks

- [x] 글쓰기 페이지 useMutation 로직 삭제
- [x] 글쓰기 전송 axios post만 등록
- [x] 페이지 밀리는 CSS 처리
