### ISSUE TITLE
프로필 페이지 전체적인 수정

### ISSUE THREAD

**Issue by kod0751** [prgrms-fe-devcourse/NFE1-1-3-Calmiary#69]
## 💡Description
프로필 페이지의 고쳐할 부분들 수정
## ✅ Tasks
- [x] 포스트 고민글이 많아질 경우 ... 표시
- [x] 메인페이지 이미지 로딩되는 동안 대체 이미지
- [x] 각 포스트 페이지 클릭시 디테일 페이지로 경로 이어주기
- [x] 유저정보수정 페이지 유효성검사 오류 메시지 색상변경
- [x] 유저정보수정 페이지 뒤로가기 버튼 추가
- [x] alert를 모달창으로 변경(UI개선)
