### ISSUE TITLE
UX 개선

### ISSUE THREAD

**Issue by zelkovaria** [prgrms-fe-devcourse/NFE1-1-3-Calmiary#81]
## 💡Description
리팩토링시 추가할 UX

## ✅ Tasks
- [ ] 회원가입시 프로필이미지 설정 가능
- [ ] `Skeleton` 혹은 `Spinner` 적용
- [ ] 모달창 바깥 부분 클릭시 닫힘 동작
- [ ] OG 설정
- [ ] GA 설정
- [ ] 커뮤니티 댓글 삭제
- [ ] 유저간 채팅
