### ISSUE TITLE
UI 개선

### ISSUE THREAD

**Issue by zelkovaria** [prgrms-fe-devcourse/NFE1-1-3-Calmiary#82]
## 💡Description
리팩터링시 추가할 UI 개선사항들

## ✅ Tasks
- [ ] Navibation bar 이미지 크기 통일
- [ ] 글쓰기 페이지 배경 이미지 보이도록 설정
- [ ] 글쓰기 페이지에서 글쓰기 페이지로 이동할 때, 랜딩 페이지로 이동하는 부분 수정
